AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'spec/dummy/**/*'
    - 'tmp/**/*'
    - 'db/migrate/**/*'

# Allow empty files
Lint/EmptyFile:
  Enabled: false

# Allow development dependencies in gemspec
Gemspec/DevelopmentDependencies:
  Enabled: false

# Allow longer blocks in spec files
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

# Allow longer methods in generators and helpers  
Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'lib/generators/**/*'
    - 'app/helpers/**/*'

# Documentation is not required for this gem
Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 250
  Exclude:
    - 'spec/**/*'

# Increase ABC size for Rails controllers
Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'spec/**/*'

# Increase cyclomatic complexity
Metrics/CyclomaticComplexity:
  Max: 8

# Increase perceived complexity
Metrics/PerceivedComplexity:
  Max: 10

Metrics/ModuleLength:
  Max: 150

# Allow longer lines for readability
Layout/LineLength:
  Max: 230
  Exclude:
    - 'spec/**/*'

# Allow empty lines around class body
Layout/EmptyLinesAroundClassBody:
  Enabled: false

# Allow empty lines around module body
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# Allow frozen string literal comments
Style/FrozenStringLiteralComment:
  Enabled: true

# Allow rescue without specifying error class in controllers
Style/RescueStandardError:
  Exclude:
    - 'app/controllers/**/*'

# Allow using `each` instead of `for`
Style/For:
  Enabled: false

# Allow multiple assignments
Style/ParallelAssignment:
  Enabled: false

# Disable class equality comparison cop for controllers
# We need to compare class names as strings when filtering by URL parameters
Style/ClassEqualityComparison:
  Exclude:
    - 'app/controllers/**/*'