AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'spec/dummy/**/*'
    - 'tmp/**/*'
    - 'db/migrate/**/*'

# Allow empty files
Lint/EmptyFile:
  Enabled: false

# Allow development dependencies in gemspec
Gemspec/DevelopmentDependencies:
  Enabled: false

# Allow longer blocks in spec files
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

# Allow longer methods in generators, helpers, and controllers
Metrics/MethodLength:
  Max: 25  # Increased from 15 to 25
  Exclude:
    - 'lib/generators/**/*'
    - 'app/helpers/**/*'
    - 'app/controllers/**/*'  # Added controllers
    - 'lib/recycle_bin.rb'    # Added main module

# Documentation is not required for this gem
Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 250
  Exclude:
    - 'spec/**/*'

# Increase ABC size for Rails controllers and main module
Metrics/AbcSize:
  Max: 30  # Increased from 20 to 30
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/**/*'  # Added controllers
    - 'lib/recycle_bin.rb'    # Added main module

# Increase cyclomatic complexity for complex pagination logic
Metrics/CyclomaticComplexity:
  Max: 12  # Increased from 8 to 12
  Exclude:
    - 'app/controllers/**/*'
    - 'lib/recycle_bin.rb'

# Increase perceived complexity for pagination and filtering logic
Metrics/PerceivedComplexity:
  Max: 12  # Increased from 10 to 12
  Exclude:
    - 'app/controllers/**/*'
    - 'lib/recycle_bin.rb'

Metrics/ModuleLength:
  Max: 200  # Increased from 150 to 200

# Allow longer lines for readability
Layout/LineLength:
  Max: 230
  Exclude:
    - 'spec/**/*'

# Allow empty lines around class body
Layout/EmptyLinesAroundClassBody:
  Enabled: false

# Allow empty lines around module body
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# Allow frozen string literal comments
Style/FrozenStringLiteralComment:
  Enabled: true

# Allow rescue without specifying error class in controllers
Style/RescueStandardError:
  Exclude:
    - 'app/controllers/**/*'

# Allow using `each` instead of `for`
Style/For:
  Enabled: false

# Allow multiple assignments
Style/ParallelAssignment:
  Enabled: false

# Disable class equality comparison cop for controllers
# We need to compare class names as strings when filtering by URL parameters
Style/ClassEqualityComparison:
  Exclude:
    - 'app/controllers/**/*'

# Allow ComparableClamp style for our specific use case
Style/ComparableClamp:
  Exclude:
    - 'app/controllers/**/*'  # Our clamp logic is clear and readable

# Allow accessor method names starting with get_ for semantic clarity
Naming/AccessorMethodName:
  Exclude:
    - 'app/controllers/**/*'  # get_all_model_types is semantically clear